### ISSUE TITLE
OAuth Redirect URI Mismatch - Redirects to Localhost in Production

### ISSUE THREAD

**Issue by kartik2005221** [Sohan-Rout/DsaVisualizer#9]
When attempting to sign in with Google, after selecting a Google account, the application incorrectly redirects to `http://localhost:3000` with an authorization code (e.g., `?code=ba105863-7f77-4aa7-981c-61fe1142c41e`). This suggests the OAuth configuration is still using development settings in a production/deployed environment.  

**Steps to Reproduce:**  
1. Go to the login page  
2. Click "Sign in with Google"  
3. Select a Google account  
4. Observe the redirect to `http://localhost:3000` instead of the production domain  

**Expected Behavior:**  
Should redirect to the production domain URL after OAuth flow.  

**Possible Fixes Needed:**  
- Update authorized redirect URIs in Google Cloud Console  
- Ensure environment variables/configuration files use production endpoints  
- Verify the OAuth client ID corresponds to the deployment environment

**Comment by Sohan-Rout** [comment]
fixed redirection issue

**Comment by kartik2005221** [comment]
but, issue is still present, after login my id vgrah is not showing up...!

**Comment by Sohan-Rout** [comment]
nope its not an issue I didnt build the dashboard part yet I have just setup the login and signup infrastructure

**Comment by kartik2005221** [comment]
ok then
